{% set name = "sse2neon" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DLTcollab/sse2neon/archive/v{{ version }}.tar.gz
  sha256: e251746e3b761f3f0de1ad462b1efe53532341b6b0498d394765fceb85ce8a46

build:
  number: 0

requirements:
  build:
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/sse2neon/sse2neon.h  # [unix]
    - if not exist %LIBRARY_PREFIX%/include/sse2neon/sse2neon.h exit 1  # [win]

about:
  home: https://github.com/DLTcollab/sse2neon
  summary: A translator from Intel SSE intrinsics to Arm/Aarch64 NEON implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
