schema_version: 1

context:
  name: sse2neon
  version: 1.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/DLTcollab/sse2neon/archive/v${{ version }}.tar.gz
  sha256: d5340e2d7bad27e4a20acc72b8ad0ec538e5e502980194b691cad2f0ab10cb8a

build:
  number: 0

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/include/sse2neon/sse2neon.h
      - if: win
        then: if not exist %LIBRARY_PREFIX%/include/sse2neon/sse2neon.h exit 1

about:
  summary: A translator from Intel SSE intrinsics to Arm/Aarch64 NEON implementation
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/DLTcollab/sse2neon

extra:
  recipe-maintainers:
    - xhochy
