github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  osx_arm64: linux_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
bot:
  automerge: true
conda_install_tool: pixi
conda_build_tool: rattler-build
